import {useState} from 'react';
import type {PublicSnapshot} from '../shared/public-model.ts';
import {distribution,statusDistribution,sourceGroup,timeSeries,type Analytics} from './analytics.ts';
import {BarChart,LineChart} from './Charts.tsx';
import {cohorts,primaryFamily,outcomeLocation,scoreBucket,appliedFreshness,cumulativeSeries,actionableInsights} from './outcomes.ts';
import {CohortTable,SkillsPanel,ActivityHeatmap} from './OutcomePanels.tsx';
export function Summary({data}:{data:Analytics}){return <div className="metrics">{[['Applications today',data.todayCount],['This week',data.thisWeek],['Interviews ever',data.interviews],['🔥 Current streak',`${data.current} ${data.current===1?'day':'days'}`]].map(([label,value])=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>;}
export function ActivityLine({data,initial=30}:{data:Analytics;initial?:number}){
  const [period,setPeriod]=useState<number|'all'>(initial),rows=timeSeries(data,period);
  return <section><div className="period no-print" aria-label="Application activity period">{([7,30,90,'all'] as const).map(p=><button key={p} className={period===p?'':'secondary'} aria-pressed={period===p} onClick={()=>setPeriod(p)}>{p==='all'?'All':`${p}D`}</button>)}</div><LineChart title={`Application activity — ${period==='all'?'all time':period+' days'}`} labels={rows.map(r=>r[0])} series={[{name:'Applications',values:rows.map(r=>r[1])}]}/></section>;
}
export function Overview({data}:{data:Analytics}){return <><Summary data={data}/><div className="charts"><ActivityLine data={data} initial={7}/><BarChart title="Current application statuses" rows={statusDistribution(data.applications)} horizontal/></div></>;}
export function AnalyticsView({snapshot,data}:{snapshot:PublicSnapshot;data:Analytics}){
  const [period,setPeriod]=useState<number|'all'>(30);const cumulative=cumulativeSeries(data,period);
  const insights=actionableInsights(data.applications);
  const currentEstimates=data.applications.filter(j=>!j.applicationFacts).length;
  return <section className="analytics-report"><div className="section-heading"><h2>Application analytics</h2><button className="no-print" onClick={()=>window.print()}>Print Analytics</button></div>
    <p className="muted">Generated {new Date().toLocaleString()} · Data published {snapshot.exportedAt} · Calendar timezone {data.timeZone}</p>
    <div className="analytics-links no-print">{[['overview','Overview'],['activity','Activity'],['applying','What I’m Applying To'],['working','What’s Working'],['funnel','Funnel']].map(([id,label])=><a key={id} href={`#analytics-${id}`}>{label}</a>)}</div>
    <h2 id="analytics-overview">Overview</h2><Summary data={data}/><div className="metrics">{[['Discovered',snapshot.totalDiscovered??'Unavailable'],['Total applications',data.applications.length],['Rejected (current)',data.rejected],['Offers ever',data.offers],['This month',data.thisMonth],['Longest streak',`${data.longest} days`],['Interview conversion',data.conversion===null?'No applications':`${data.conversion.toFixed(1)}%`],['Average / active day',data.average.toFixed(1)]].map(([label,value])=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
    <p className="muted">Rates use applications with evidence of reaching Interview, including later outcomes. One application per canonical opportunity; an offer does not imply an unrecorded interview. {data.unknownDates} unknown application dates and {data.futureDates} future dates are excluded from daily activity. Current streak includes yesterday if today has no activity yet.</p>
    <h2 id="analytics-activity">Activity</h2><ActivityLine data={data}/><ActivityHeatmap data={data}/>
    <div className="period no-print"><label>Cumulative period <select aria-label="Cumulative period" value={period} onChange={e=>setPeriod(e.target.value==='all'?'all':Number(e.target.value))}>{[7,30,90,'all'].map(p=><option key={p} value={p}>{p==='all'?'All':`${p}D`}</option>)}</select></label></div>
    <LineChart title="Cumulative applications and interviews" labels={cumulative.map(r=>r.day)} series={[{name:'Applications',values:cumulative.map(r=>r.applications)},{name:'Interviews',values:cumulative.map(r=>r.interviews)}]}/>
    <p className="muted">Cumulative totals include activity before the selected window. Interviews are added on the actual interview-stage date, not the application date. Undated interviews cannot be placed on this chart.</p>
    <div className="trend"><h3>Recent activity</h3><p>This week to date: <strong>{data.thisWeek}</strong> · Same weekdays last week: <strong>{data.previousComparable}</strong> · Change: <strong>{data.trend===null?'No prior baseline':`${data.trend>=0?'+':''}${data.trend.toFixed(1)}%`}</strong></p><p className="muted">Monday-based weeks. Previous full week: {data.previousWeek}. Missing tracking history cannot prove inactivity.</p></div>
    <h2 id="analytics-applying">What I’m Applying To</h2><SkillsPanel data={data}/><div className="charts"><BarChart title="Current status distribution" rows={statusDistribution(data.applications)} horizontal/><BarChart title="Opportunity types" rows={distribution(data.applications,j=>j.type.toLowerCase())} horizontal/></div>
    <h2 id="analytics-working">What’s Working</h2><p className="muted">All rates show their denominators. Pending applications and small samples limit interpretation; these are associations, not causal findings. Sources are assigned once using the canonical link. Skill groups can overlap.</p>
    <section className="chart-panel"><h3>Evidence worth reviewing</h3>{insights.length?<ul>{insights.flatMap(group=>group.rows.map(row=><li key={group.dimension+row.name}>{group.dimension} · {row.name}: <strong>{row.applications} applications → {row.interviews} interviews ({row.rate.toFixed(1)}%)</strong></li>))}</ul>:<p>No group has at least 10 applications yet. Keep tracking outcomes before comparing rates.</p>}<p className="muted">Only groups with at least 10 applications are shown. These are observed rates, not predictions. Pending applications lower current rates; groups can overlap.</p></section>
    <CohortTable title="Role families — applications and interview rate" rows={cohorts(data.applications,j=>[primaryFamily(j)])}/>
    <CohortTable title="Sources — applications and interview rate" rows={cohorts(data.applications,j=>[sourceGroup(j)])}/>
    <CohortTable title="Locations — applications and interview rate" rows={cohorts(data.applications,j=>[outcomeLocation(j)])}/>
    <CohortTable title="Match-score buckets vs interview rate" rows={cohorts(data.applications,j=>[scoreBucket(j)]).sort((a,b)=>a.name.localeCompare(b.name))}/>
    <CohortTable title="Job freshness when applied vs interview rate" rows={cohorts(data.applications,j=>[appliedFreshness(j)])}/>
    <p className="muted">{currentEstimates} applications predate application-time snapshots: their score, skills and freshness use current listing data as estimates. New applications freeze these facts. Freshness uses the source’s posted/last-published date; it never substitutes first-seen or update dates. Missing dates or a later republication are Unknown.</p>
    <h2 id="analytics-funnel">Funnel</h2><section className="chart-panel"><div className="funnel"><span>{snapshot.totalDiscovered??'—'} Discovered</span><span>→ {data.applications.length} Applied</span><span>→ {data.interviews} Interviewed</span><span>→ {data.offers} Offers</span></div><p className="muted">Discovered includes filtered jobs. These are recorded stage totals, not proof that every job passed through every preceding stage.</p></section>
  </section>;
}
