import {useState} from 'react';
import type {PublicSnapshot} from '../shared/public-model.ts';
import {distribution,statusDistribution,locationGroup,reached,sourceGroup,timeSeries,type Analytics} from './analytics.ts';
import {BarChart} from './Charts.tsx';
export function Summary({data}:{data:Analytics}){return <div className="metrics">{[['Applications today',data.todayCount],['This week',data.thisWeek],['Interviews ever',data.interviews],['🔥 Current streak',`${data.current} ${data.current===1?'day':'days'}`]].map(([label,value])=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>;}
export function Overview({data}:{data:Analytics}){return <><Summary data={data}/><div className="charts"><BarChart title="Applications — last 7 days" rows={timeSeries(data,7)}/><BarChart title="Current application statuses" rows={statusDistribution(data.applications)} horizontal/></div></>;}
export function AnalyticsView({snapshot,data}:{snapshot:PublicSnapshot;data:Analytics}){
  const [period,setPeriod]=useState<number|'all'>(30);
  const weekdayNames=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
  const weekdays: [string,number][]=weekdayNames.map((name,i)=>[name,[...data.daily].reduce((n,[day,jobs])=>n+(((new Date(day+'T12:00:00Z').getUTCDay()+6)%7)===i?jobs.length:0),0)]);
  const buckets=[[0,49],[50,59],[60,69],[70,79],[80,89],[90,100]].map(([min,max])=>{const jobs=data.applications.filter(j=>j.matchScore>=min&&j.matchScore<=max);return {label:`${min}–${max}%`,applications:jobs.length,interviews:jobs.filter(j=>reached(j,'INTERVIEW')).length};});
  return <section className="analytics-report"><div className="section-heading"><h2>Application analytics</h2><button className="no-print" onClick={()=>window.print()}>Print Analytics</button></div>
    <p className="muted">Report generated {new Date().toLocaleString()} · Data as of {snapshot.exportedAt} · Calendar timezone: {data.timeZone}</p>
    <Summary data={data}/><div className="metrics">{[['Opportunities discovered',snapshot.totalDiscovered??'Unavailable'],['Total applications',data.applications.length],['Rejected (current)',data.rejected],['Offers ever',data.offers],['This month',data.thisMonth],['🏆 Longest streak',`${data.longest} ${data.longest===1?'day':'days'}`],['Interview conversion',data.conversion===null?'No applications':`${data.conversion.toFixed(1)}%`],['Average / active day',data.average.toFixed(1)]].map(([label,value])=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
    <p className="muted">One application per opportunity. Interview conversion counts applications with recorded interview evidence, including later outcomes. Offers do not imply an unrecorded interview. Discovered is the deduplicated local database total, including filtered jobs. Match scores are current, not scores frozen at application time.</p>
    <p className="muted">Streaks remain active if you applied today or yesterday. Weeks start Monday. {data.unknownDates} applications with unknown dates and {data.futureDates} future-dated records are excluded from activity totals.</p>
    <div className="trend"><h3>Recent activity</h3><p>This week to date: <strong>{data.thisWeek}</strong> · Same weekdays last week: <strong>{data.previousComparable}</strong> · Change: <strong>{data.trend===null?(data.thisWeek?'No prior baseline':'No activity in either period'):`${data.trend>=0?'+':''}${data.trend.toFixed(1)}%`}</strong></p><p className="muted">Previous full week: {data.previousWeek}. Comparison uses recorded activity only; missing tracking history cannot prove inactivity.</p></div>
    <label className="period no-print">Applications over time <select aria-label="Chart period" value={period} onChange={e=>setPeriod(e.target.value==='all'?'all':Number(e.target.value))}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="all">All time</option></select></label>
    <div className="charts"><BarChart title={`Applications over time — ${period==='all'?'all recorded dates':period+' days'}`} rows={timeSeries(data,period)}/><BarChart title="Applications by current status" rows={statusDistribution(data.applications)} horizontal/><BarChart title="Applications by location" rows={distribution(data.applications,j=>locationGroup(j.location,j.remoteType))} horizontal/><BarChart title="Applications by opportunity type" rows={distribution(data.applications,j=>j.type.toLowerCase())} horizontal/><BarChart title="Applications by canonical source" rows={distribution(data.applications,sourceGroup)} horizontal/><BarChart title="Activity by day of week" rows={weekdays}/></div>
    <section className="chart-panel"><h3>Recorded progression</h3><div className="funnel"><span>{snapshot.totalDiscovered??'—'} Discovered</span><span>→ {data.applications.length} Applied</span><span>→ {data.interviews} Interviewed</span><span>→ {data.offers} Offers</span></div><p className="muted">Descriptive totals, not a causal funnel. Outcomes may be recorded without every preceding stage; sources and roles have different selection effects.</p></section>
    <section className="chart-panel"><h3>Match score vs outcome</h3>{data.applications.length<5?<p>At least 5 recorded applications are needed for this comparison. There are currently {data.applications.length}.</p>:<table><thead><tr><th>Current score</th><th>Applications</th><th>Interviewed</th><th>Interview rate</th></tr></thead><tbody>{buckets.map(b=><tr key={b.label}><td>{b.label}</td><td>{b.applications}</td><td>{b.interviews}</td><td>{b.applications?`${(100*b.interviews/b.applications).toFixed(1)}%`:'—'}</td></tr>)}</tbody></table>}<p className="muted">Small samples and unresolved applications limit this comparison. It does not establish that a higher score caused an interview.</p></section>
  </section>;
}
