import {useState} from 'react';
import type {Analytics} from './analytics.ts';
import {shiftDay} from './analytics.ts';
import {cohorts,skillsFor,type Cohort} from './outcomes.ts';
import {BarChart} from './Charts.tsx';
export function CohortTable({title,rows}:{title:string;rows:Cohort[]}){return <section className="chart-panel"><h3>{title}</h3>{!rows.length?<p>No recorded applications yet.</p>:<div className="table-scroll"><table><thead><tr><th>Group</th><th>Applications</th><th>Interviewed</th><th>Interview rate</th></tr></thead><tbody>{rows.map(r=><tr key={r.name}><td>{r.name}</td><td>{r.applications}</td><td>{r.interviews}</td><td><span className="rate-track"><span style={{width:r.rate+'%'}}/></span>{r.rate.toFixed(1)}%{r.applications<5&&<small> · small sample</small>}</td></tr>)}</tbody></table></div>}</section>;}
export function SkillsPanel({data}:{data:Analytics}){
  const [metric,setMetric]=useState('Applications'),[minimum,setMinimum]=useState(1);
  const all=cohorts(data.applications,skillsFor),rows=all.filter(r=>r.applications>=minimum).sort((a,b)=>metric==='Interview Rate'?b.rate-a.rate||b.applications-a.applications:metric==='Interviews'?b.interviews-a.interviews||b.applications-a.applications:b.applications-a.applications).slice(0,20);
  return <section><h3>Skills in application job descriptions</h3><div className="period no-print"><label>Measure <select aria-label="Skills measure" value={metric} onChange={e=>setMetric(e.target.value)}>{['Applications','Interviews','Interview Rate'].map(v=><option key={v}>{v}</option>)}</select></label><label>Minimum applications <select aria-label="Skills minimum sample" value={minimum} onChange={e=>setMinimum(Number(e.target.value))}>{[1,3,5,10].map(v=><option key={v}>{v}</option>)}</select></label></div><BarChart title={`Top 20 skills — ${metric}${metric==='Interview Rate'?' (%)':''}`} rows={rows.map(r=>[r.name,metric==='Applications'?r.applications:metric==='Interviews'?r.interviews:Number(r.rate.toFixed(1))])} horizontal valueLabel={metric==='Interview Rate'?'Interview rate (%)':metric}/><CohortTable title="Skill evidence and sample sizes" rows={rows}/><p className="muted">Counts are applications mentioning a skill, not your proficiency or a requirement classification. One job can mention several skills. Full job keywords are used when available; older snapshots may contain only matched skills. Rates include pending applications and are descriptive.</p></section>;
}
export function ActivityHeatmap({data}:{data:Analytics}){
  const [selected,setSelected]=useState(data.today),start=shiftDay(data.today,-370),jobs=data.daily.get(selected)??[];
  return <section className="chart-panel"><h3>Daily activity — last 53 weeks</h3><div className="heatmap" aria-label="Daily application heatmap">{Array.from({length:371},(_,i)=>shiftDay(start,i)).map(day=>{const n=data.daily.get(day)?.length??0;return <button key={day} className={`heat-cell heat-${Math.min(4,Math.ceil(n/3))}`} title={`${day}: ${n} applications`} aria-label={`${day}: ${n} applications`} aria-pressed={selected===day} onClick={()=>setSelected(day)}/>;})}</div><p className="muted">Less ▫ ▪ More · {data.timeZone} · Each column is seven consecutive days. Select a day for details.</p><p><strong>{selected}: {jobs.length} applications</strong></p>{jobs.length>0&&<ul>{jobs.map(j=><li key={j.id}>{j.company} — {j.title} · {j.status}{j.applicationUrl&&<> · <a href={j.applicationUrl} target="_blank" rel="noopener noreferrer">Original job ↗</a></>}</li>)}</ul>}</section>;
}
